global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node
    static_configs:
      - targets: ['XXX:9100']
        labels: { instance: node01 }
      - targets: ['XXX:9100' ]
        labels: { instance: node02 }
      - targets: ['XXX:9100' ]
        labels: { instance: node03 }

  - job_name: cadvisor
    static_configs:
      - targets: ['XXX:8080']
        labels: { instance: node01 }
      - targets: ['XXX:8080' ]
        labels: { instance: node02 }
      - targets: ['XXX:8080' ]
        labels: { instance: node03 }

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
