---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: true
  become: true

- name: Enable & start Docker
  systemd:
    name: docker
    enabled: true
    state: started
  become: true