server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          instance: ${HOSTNAME}
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - docker: {}
      - labeldrop: [stream]
      - drop:
          expression: '^\s*$'

  - job_name: varlogs
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs
          instance: ${HOSTNAME}
          __path__: /var/log/*log
